### ISSUE TITLE
Error unknown keyword: :thread_safe

### ISSUE THREAD

**Issue by yangjiel** [pokehanai/fluent-plugin-redis-store#12]
Hi,

I encountered an error when using this fluentd output plugin. My environment are:
Redis server v=7.0.8 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=2d3daf4cfae9428f
td-agent 4.4.1 fluentd 1.15.2 (c32842297ed2c306f1b841a8f6e55bdd0f1cb27f)

Confirmed redis is working:
```
$ redis-cli -p 6379
127.0.0.1:6379>
```
My fluentd config is:
```
<match **>
  @type redis_store
  key test
</match>
```

After I ran the fluentd, I got this error:
```
2023-02-02 17:02:13 -0800 [error]: Worker 0 finished unexpectedly with status 1
2023-02-02 17:02:14 -0800 [info]: adding match pattern="**" type="copy"
2023-02-02 17:02:14 -0800 [warn]: #0 define <match fluent.**> to capture fluentd logs in top level is deprecated. Use <label @FLUENT_LOG> instead
2023-02-02 17:02:14 -0800 [info]: #0 starting fluentd worker pid=77595 ppid=77512 worker=0
2023-02-02 17:02:14 -0800 [error]: #0 unexpected error error_class=ArgumentError error="unknown keyword: :thread_safe"
  2023-02-02 17:02:14 -0800 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/redis-client-0.12.1/lib/redis_client/config.rb:21:in `initialize'
  2023-02-02 17:02:14 -0800 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/redis-client-0.12.1/lib/redis_client/config.rb:182:in `initialize'
  2023-02-02 17:02:14 -0800 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/redis-client-0.12.1/lib/redis_client.rb:142:in `new'
  2023-02-02 17:02:14 -0800 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/redis-client-0.12.1/lib/redis_client.rb:142:in `config'
  2023-02-02 17:02:14 -0800 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/redis-5.0.6/lib/redis/client.rb:23:in `config'
  2023-02-02 17:02:14 -0800 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/redis-5.0.6/lib/redis.rb:157:in `initialize_client'
  2023-02-02 17:02:14 -0800 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/redis-5.0.6/lib/redis.rb:73:in `initialize'
  2023-02-02 17:02:14 -0800 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-redis-store-0.2.0/lib/fluent/plugin/out_redis_store.rb:60:in `new'
  2023-02-02 17:02:14 -0800 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-redis-store-0.2.0/lib/fluent/plugin/out_redis_store.rb:60:in `start'
  2023-02-02 17:02:14 -0800 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.2/lib/fluent/root_agent.rb:203:in `block in start'
  2023-02-02 17:02:14 -0800 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.2/lib/fluent/root_agent.rb:192:in `block (2 levels) in lifecycle'
  2023-02-02 17:02:14 -0800 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.2/lib/fluent/root_agent.rb:191:in `each'
  2023-02-02 17:02:14 -0800 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.2/lib/fluent/root_agent.rb:191:in `block in lifecycle'
  2023-02-02 17:02:14 -0800 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.2/lib/fluent/root_agent.rb:178:in `each'
  2023-02-02 17:02:14 -0800 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.2/lib/fluent/root_agent.rb:178:in `lifecycle'
  2023-02-02 17:02:14 -0800 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.2/lib/fluent/root_agent.rb:202:in `start'
  2023-02-02 17:02:14 -0800 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.2/lib/fluent/engine.rb:248:in `start'
  2023-02-02 17:02:14 -0800 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.2/lib/fluent/engine.rb:147:in `run'
  2023-02-02 17:02:14 -0800 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.2/lib/fluent/supervisor.rb:764:in `block in run_worker'
  2023-02-02 17:02:14 -0800 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.2/lib/fluent/supervisor.rb:1037:in `main_process'
  2023-02-02 17:02:14 -0800 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.2/lib/fluent/supervisor.rb:755:in `run_worker'
  2023-02-02 17:02:14 -0800 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.2/lib/fluent/command/fluentd.rb:381:in `<top (required)>'
  2023-02-02 17:02:14 -0800 [error]: #0 /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'  2023-02-02 17:02:14 -0800 [error]: #0 /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'  2023-02-02 17:02:14 -0800 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.2/bin/fluentd:15:in `<top (required)>'
  2023-02-02 17:02:14 -0800 [error]: #0 /opt/td-agent/bin/fluentd:23:in `load'
  2023-02-02 17:02:14 -0800 [error]: #0 /opt/td-agent/bin/fluentd:23:in `<top (required)>'
  2023-02-02 17:02:14 -0800 [error]: #0 /usr/sbin/td-agent:15:in `load'
  2023-02-02 17:02:14 -0800 [error]: #0 /usr/sbin/td-agent:15:in `<main>'
2023-02-02 17:02:14 -0800 [error]: #0 unexpected error error_class=ArgumentError error="unknown keyword: :thread_safe"
```

I wonder if anyone has the same issue? Or is my config wrong? Thanks.

**Comment by dmytro-shevchenko** [comment]
Hi @yangjiel 

fluent-plugin-redis-store as a dependency use "redis" gem. In your output it version is 5.0.6. Since "redis" version 5.0.0 this gem has a dependency to "redis-client", and this breaks fluent-plugin-redis-store, as "redis-client" doesn't support parameter "thread_safe".

Solution: Downgrade "redis" gem < 5.0.0
```
/usr/sbin/td-agent-gem uninstall redis redis-client
/usr/sbin/td-agent-gem install redis -v 4.8.1
```

**Comment by yangjiel** [comment]
Thanks for the info, close the issue for now.
